# Generated by Django 4.2.11 on 2024-03-07 19:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('birthdate', models.DateField(verbose_name="Date d'anniversaire")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de téléphone')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('degree', models.CharField(max_length=200)),
                ('year_of_graduation', models.DateField(verbose_name="Date de l'obtention du diplôme")),
                ('institution', models.CharField(max_length=100, verbose_name="Nom de l'école")),
                ('position', models.CharField(max_length=100, verbose_name='Titre du poste occupé')),
                ('company', models.CharField(max_length=100, verbose_name='Nom de la société')),
                ('hiring_date', models.DateField(verbose_name="Date d'embauche")),
            ],
        ),
    ]
