# Generated by Django 4.2.11 on 2024-03-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(help_text="Veuillez entrer une adresse mail valide s'il vous plaît", max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('message', models.TextField(blank=True, max_length=5000, verbose_name='Message')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande des clients',
            },
        ),
        migrations.AlterModelOptions(
            name='carouselportfolioimage',
            options={'verbose_name': 'Carousel image'},
        ),
        migrations.AlterModelOptions(
            name='expertiseframework',
            options={'verbose_name': 'Framework'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio'},
        ),
    ]
