# Generated by Django 4.2.11 on 2024-03-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0002_form_alter_carouselportfolioimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Demande des client'},
        ),
    ]
