# Generated by Django 4.2.11 on 2024-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0002_alter_information_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(default=0, upload_to='pics_on_myself/'),
            preserve_default=False,
        ),
    ]
