# Generated by Django 4.2.11 on 2024-03-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0004_rename_form_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
