# Generated by Django 4.2.11 on 2024-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0005_alter_expertiselanguage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertiselanguage',
            name='image',
            field=models.ImageField(blank=True, upload_to='language_image/'),
        ),
    ]
