# Generated by Django 4.2.11 on 2024-03-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0006_alter_expertiselanguage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertiselanguage',
            name='image',
        ),
    ]
