# Generated by Django 4.2.11 on 2024-03-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0007_alter_information_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titre de la section')),
                ('post_title', models.CharField(max_length=100, verbose_name='Intitulé du poste')),
                ('post_date_start', models.DateField(verbose_name="Date d'embauche")),
                ('post_date_end', models.DateField(verbose_name='Date de fin')),
                ('type_of_service', models.CharField(help_text='Dire si vous étiez en freelance, consultant etc...', max_length=50, verbose_name='Type de service')),
                ('post_description', models.TextField(help_text='Dire en quoi consistait le travail', max_length=2000, verbose_name='Description du poste')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_informations.information')),
            ],
            options={
                'verbose_name': 'Carousel image',
            },
        ),
    ]
