# Generated by Django 4.2.11 on 2024-03-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0008_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='portfolio',
            new_name='information',
        ),
    ]
