# Generated by Django 4.2.11 on 2024-03-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0009_rename_portfolio_resume_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Expériences'},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='post_title',
        ),
    ]
