# Generated by Django 4.2.11 on 2024-03-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0010_alter_resume_options_remove_resume_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Expérience', 'verbose_name_plural': 'Expériences'},
        ),
    ]
