# Generated by Django 4.2.13 on 2024-06-18 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0012_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='description_second',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
