# Generated by Django 4.2.13 on 2024-06-18 12:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0013_information_description_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='description_second',
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=1000, verbose_name='A propos de moi'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='post_description',
            field=ckeditor.fields.RichTextField(default='', help_text='Dire en quoi consistait le travail', max_length=2000, verbose_name='Description du poste'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=ckeditor.fields.RichTextField(default='', help_text='Donner la description du service', max_length=1000, verbose_name='Description du poste'),
        ),
    ]
