# Generated by Django 4.2.13 on 2024-06-18 12:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0014_remove_information_description_second_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=300, verbose_name='Description'),
        ),
    ]
