# Generated by Django 4.2.13 on 2024-06-18 12:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_informations', '0015_alter_portfolio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Donner la description du service', max_length=1000, verbose_name='Description du poste'),
        ),
    ]
